### ISSUE TITLE
Steps to setup

### ISSUE THREAD

**Issue by joeblew99** [bobinette/papernet#12]
this is nice for tracking papers.

but am lost with setting up locally.

can you add basic step to setup in readme  or here ?

**Comment by bobinette** [comment]
Hello!

Sorry for this late reply, I'm not used to people writing here. Sure, I'll add a basic setup to the readme 👍 

Otherwise, if you are not scared of having your notes online, you can check out https://papernet.bobi.space!

**Comment by joeblew99** [comment]
thanks that woudl be great.

**Comment by bobinette** [comment]
Just pushed it, is it good for you?

**Comment by joeblew99** [comment]
Yep sweet. Thanks.
I do biology work so this is really useful !!

**Comment by bobinette** [comment]
Awesome! Thanks for the feedback, and do not hesitate if you have some more 😉
