### ISSUE TITLE
Refresh user information from google

### ISSUE THREAD

**Issue by bobinette** [bobinette/papernet#13]
Now that I need the email, I need to ask the user to log out and log in again to get it from Google. It would be better to be able to refresh the user information through a Papernet end point.

Check this [link](http://stackoverflow.com/questions/28685033/how-to-handle-refresh-tokens-in-golang-ouath2-client-lib).

**Comment by joeblew99** [comment]
ah i got the same issue when i tried the web gui :)

**Comment by bobinette** [comment]
Hmm, not sure what you mean. Did you have an error logging in to the website?

**Comment by bobinette** [comment]
I just found the error, it should be ok to sign up now
