### ISSUE TITLE
setup error: FATA[0000] could not open key file: open configuration/hs256.json: no such file or directory  env=dev

### ISSUE THREAD

**Issue by joeblew99** [bobinette/papernet#18]
on clean setup....
seems i need a config.

````
x-MacBook-Pro:papernet apple$ mkdir data
x-MacBook-Pro:papernet apple$ go run cmd/cli/*.go index create --index=data/papernet.index --mapping=bleve/mapping.json
Index created at data/papernet.index
x-MacBook-Pro:papernet apple$ go run cmd/web/main.go
../../gin-gonic/gin/binding/default_validator.go:7:2: cannot find package "gopkg.in/go-playground/validator.v8" in any of:
	/usr/local/opt/go/libexec/src/gopkg.in/go-playground/validator.v8 (from $GOROOT)
	/Users/apple/workspace/go/src/gopkg.in/go-playground/validator.v8 (from $GOPATH)
x-MacBook-Pro:papernet apple$ go get gopkg.in/go-playground/validator.v8
x-MacBook-Pro:papernet apple$ go run cmd/web/main.go
FATA[0000] could not open key file: open configuration/hs256.json: no such file or directory  env=dev
exit status 1
x-MacBook-Pro:papernet apple$ go run cmd/cli/*.go index create --index=data/papernet.index --mapping=bleve/mapping.json
Index data/papernet.index already exists, no need to create it
x-MacBook-Pro:papernet apple$ go run cmd/web/main.go
FATA[0000] could not open key file: open configuration/hs256.json: no such file or directory  env=dev
exit status 1

````

so i figured maybe the CLI allows me to create my auth key. But no luck..
```
x-MacBook-Pro:papernet apple$ go run cmd/cli/*.go auth
FATA[0000] could not open key file: open configuration/hs256.json: no such file or directory  env=dev
exit status 1
```

**Comment by joeblew99** [comment]
is there a CLi command to create the required hs256.json credrentials ?
Or some readme instructions ?

**Comment by bobinette** [comment]
Indeed, it is not specified anywhere. I'll add that to the README :+1:
I used https://mkjwk.org/ to generate it with the following:
![image](https://cloud.githubusercontent.com/assets/9349295/26157368/53806e4e-3b19-11e7-816e-6f9f8f774a5b.png)
setting the key id to whatever

**Comment by joeblew99** [comment]
ok. I grabbed the keypair resultset ( the middle pane).
slapped it in the hs256.json file.

Now getting further 👍 

````
x-MacBook-Pro:papernet apple$ go run cmd/web/main.go
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /ping                     --> github.com/bobinette/papernet/gin.New.func3 (4 handlers)
[GIN-debug] GET    /auth/v2/me               --> github.com/bobinette/papernet/gin.wrapH.func1 (4 handlers)
[GIN-debug] POST   /auth/v2/bookmarks        --> github.com/bobinette/papernet/gin.wrapH.func1 (4 handlers)
[GIN-debug] GET    /auth/v2/teams            --> github.com/bobinette/papernet/gin.wrapH.func1 (4 handlers)
[GIN-debug] POST   /auth/v2/teams            --> github.com/bobinette/papernet/gin.wrapH.func1 (4 handlers)
[GIN-debug] DELETE /auth/v2/teams/:id        --> github.com/bobinette/papernet/gin.wrapH.func1 (4 handlers)
[GIN-debug] POST   /auth/v2/teams/:id/invite --> github.com/bobinette/papernet/gin.wrapH.func1 (4 handlers)
[GIN-debug] POST   /auth/v2/teams/:id/kick   --> github.com/bobinette/papernet/gin.wrapH.func1 (4 handlers)
[GIN-debug] POST   /auth/v2/teams/:id/share  --> github.com/bobinette/papernet/gin.wrapH.func1 (4 handlers)
FATA[0000] could not instantiate google service          env=dev
exit status 1

````

**Comment by bobinette** [comment]
Hmm oops, it seems I forgot to log the error here: https://github.com/bobinette/papernet/blob/master/cmd/web/main.go#L109
If you add it, the message will definitely be clearer

I think you are missing the google configuration to use google login. You need credentials to be able to start the server. I'll add that to the README as well, and when I have the time, make a no-auth version of it.

If you are using the front as well, I think you might be able to skip the google part already by:
- removing the lines in `web/cmd/main.go` dealing with google auth
- creating a user via the cli
- changing the initial state of the auth reducer in the front project, here: https://github.com/bobinette/papernet-front/blob/master/src/auth/reducer.js#L5 to pretend the user is loaded and already has the id you want

I don't have much time to work on it these days, but I'll fix those as soon as I can, I'll let you know here :slightly_smiling_face:

**Comment by joeblew99** [comment]
ok thanks

**Comment by bobinette** [comment]
There is now a new login system based on email and password that you can use locally instead of the Google oauth system. It does not come with email confirmation and password reset but as it is intended to be used locally only (at least for now), I do not think those features are needed 🙂

To get rid of the google oauth provider, edit the configuration:
```toml
# other stuff

[oauth.google]
enabled=false

# other stuff
```

This should do the trick. Regarding the cli, it should work as long as you do not try to use the `oauth` sub-command. Let me know if you run into more problems, I'll fix them as soon as I can 🙂

**Comment by joeblew99** [comment]
ah nice. will make it easier to get going.

As far as email confirmation and 2 factor auth its pretty easy to add that these days actually.
i use twillo (sms), but also yubikey hardware.
email libs for golang are pretty good. https://github.com/emersion/go-imap is pretty solid.

**Comment by bobinette** [comment]
I'm quite happy with Google auth in "production" so far, but if/when email confirmation is needed, I'll have a look at those :wink:

**Comment by joeblew99** [comment]
ok. maybe laters then ..
