### ISSUE TITLE
Edition mode - cursor sent to bottom of the page

### ISSUE THREAD

**Issue by Fraxoe** [bobinette/papernet#25]
Hello Bobinette,

I love your Papernet project. Great idea !

I encountered a minor (but somehow annoying) issue when editing a paper.
Blinking cursor is frequently sent to bottom of the page in edition mode (it may take a few modifications).
For that reason, when editing a paper, I can see the text above the cursor, but not what is after the cursor (unless I scroll down again). 
Sometimes it works properly. See gif.

![tmp](https://user-images.githubusercontent.com/30795547/29024327-dc3197e8-7b71-11e7-8fd2-ccb8c3aa843b.gif)

Have a great day !

Cheers, 

Fraxœ

**Comment by bobinette** [comment]
Hello @Fraxoe,

Thanks for your feedback 🙂 I'll look into that as soon as I can! If you find anything else, please do not hesitate. You can also have a look at the project of that repo to see what I'm currently working on for the backend, or here: https://github.com/bobinette/papernet-front/projects/9, for the front-end of the project.

Cheers

**Comment by bobinette** [comment]
The problem seems to be fixed now 😉

**Comment by Fraxoe** [comment]
Thank you Bobinette !
