### ISSUE TITLE
Investigate go-kit

### ISSUE THREAD

**Issue by bobinette** [bobinette/papernet#7]
Check if [go-kit](https://github.com/go-kit/kit) could be used for Papernet, especially [this example](https://github.com/go-kit/kit/tree/master/examples/shipping)

**Comment by joeblew99** [comment]
I use go kit.
Have you seen the QUIC project ?
It's network transport that's much faster.
Had good success with it

https://github.com/lucas-clemente/quic-go

**Comment by joeblew99** [comment]
I added quic to the issues list of go-kit.
Is a natural addition, but let's see.

**Comment by bobinette** [comment]
Nice! I'll have a look at that then.

**Comment by joeblew99** [comment]
its early days for QUIC. Just so you know.
